import { FunctionComponent } from 'react';

import {
  IconApple,
  IconBeer,
  IconCoins,
  IconRocket,
  IconActivity,
  TablerIconsProps,
  IconAdjustmentsHorizontal,
  IconAirBalloon,
  IconAlertCircle,
  IconAnchor,
  IconArmchair,
  IconAsset,
  IconAward,
  IconBabyBottle,
  IconBalloon,
  IconBaguette,
  IconBandage,
  IconBarbell,
  IconBat,
  IconBattery2,
  IconBasket,
  IconBell,
  IconBible,
  IconBook,
  IconBone,
  IconBookmark,
  IconBrain,
  IconBus,
  IconCactus,
  IconCake,
  IconCalculator,
  IconCampfire,
  IconCarrot,
  IconChargingPile,
  IconCheese,
  IconClock,
  IconCloud,
  IconCrown,
  IconCookie,
  IconCup,
  IconCut,
  IconDental,
  IconDeviceMobile,
  IconDeviceAirpods,
  IconDeviceTv,
  IconDeviceWatch,
  IconCat,
  IconDroplet,
  IconEgg,
  IconEye,
  IconFish,
  IconFlask,
  IconFountain,
  IconFriends,
  IconGavel,
  IconGift,
  IconHeart,
  IconHome,
  IconMap,
  IconDog,
  IconLeaf
} from '@tabler/icons-react';

export interface Icon {
  label: string;
  value: string;
  component: FunctionComponent<TablerIconsProps>;
}

// TODO: expand
// TODO: I could group them by something
export const ICONS: Icon[] = [
  { value: 'rocket', label: 'rocket', component: IconRocket },
  { value: 'coins', label: 'coins', component: IconCoins },
  { value: 'apple', label: 'apple', component: IconApple },
  { value: 'activity', label: 'activity', component: IconActivity },
  { value: 'adjustments', label: 'adjustments', component: IconAdjustmentsHorizontal },
  { value: 'air-balloon', label: 'air-balloon', component: IconAirBalloon },
  { value: 'alert', label: 'alert', component: IconAlertCircle },
  { value: 'anchor', label: 'anchor', component: IconAnchor },
  { value: 'armchair', label: 'armchair', component: IconArmchair },
  { value: 'asset', label: 'asset', component: IconAsset },
  { value: 'award', label: 'award', component: IconAward },
  { value: 'baby', label: 'baby-bottle', component: IconBabyBottle },
  { value: 'balloon', label: 'balloon', component: IconBalloon },
  { value: 'baguette', label: 'baguette', component: IconBaguette },
  { value: 'bandage', label: 'bandage', component: IconBandage },
  { value: 'barbell', label: 'barbell', component: IconBarbell },
  { value: 'bat', label: 'bat', component: IconBat },
  { value: 'battery', label: 'battery', component: IconBattery2 },
  { value: 'basket', label: 'basket', component: IconBasket },
  { value: 'beer', label: 'beer', component: IconBeer },
  { value: 'bell', label: 'bell', component: IconBell },
  { value: 'bible', label: 'bible', component: IconBible },
  { value: 'book', label: 'book', component: IconBook },
  { value: 'bone', label: 'bone', component: IconBone },
  { value: 'bookmark', label: 'bookmark', component: IconBookmark },
  { value: 'brain', label: 'brain', component: IconBrain },
  { value: 'bus', label: 'bus', component: IconBus },
  { value: 'cactus', label: 'cactus', component: IconCactus },
  { value: 'cake', label: 'cake', component: IconCake },
  { value: 'cat', label: 'cat', component: IconCat },
  { value: 'calculator', label: 'calculator', component: IconCalculator },
  { value: 'campfire', label: 'campfire', component: IconCampfire },
  { value: 'carrot', label: 'carrot', component: IconCarrot },
  { value: 'charging', label: 'charging pile', component: IconChargingPile },
  { value: 'cheese', label: 'cheese', component: IconCheese },
  { value: 'clock', label: 'clock', component: IconClock },
  { value: 'cloud', label: 'cloud', component: IconCloud },
  { value: 'cookie', label: 'cookie', component: IconCookie },
  { value: 'crown', label: 'crown', component: IconCrown },
  { value: 'cup', label: 'cup', component: IconCup },
  { value: 'cut', label: 'cut', component: IconCut },
  { value: 'dendal', label: 'dendal', component: IconDental },
  { value: 'mobile', label: 'mobile', component: IconDeviceMobile },
  { value: 'airpods', label: 'airpods', component: IconDeviceAirpods },
  { value: 'tv', label: 'tv', component: IconDeviceTv },
  { value: 'watch', label: 'watch', component: IconDeviceWatch },
  { value: 'dog', label: 'dog', component: IconDog },
  { value: 'droplet', label: 'Droplet', component: IconDroplet },
  { value: 'egg', label: 'egg', component: IconEgg },
  { value: 'eye', label: 'eye', component: IconEye },
  { value: 'fish', label: 'fish', component: IconFish },
  { value: 'flask', label: 'flask', component: IconFlask },
  { value: 'fountain', label: 'fountain', component: IconFountain },
  { value: 'friends', label: 'friends', component: IconFriends },
  { value: 'gavel', label: 'gavel', component: IconGavel },
  { value: 'gift', label: 'gift', component: IconGift },
  { value: 'heart', label: 'heart', component: IconHeart },
  { value: 'home', label: 'home', component: IconHome },
  { value: 'leaf', label: 'leaf', component: IconLeaf },
  { value: 'map', label: 'map', component: IconMap }
  // TODO: From M expand
];
